title: Hyper - The Ultimate Data Platform for IoT
email: hello@hyper.systems
description: >-
  A unified data platform to monitor, automate and manage your entire physical infrastructure in a single place.
baseurl: "/"
url: "https://www.hyper.systems"
github_username: hyper-systems

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - default.nix
  - gemset.nix
  - Makefile

collections:
  pages:
    output: true
    permalink: /:path
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title:output_ext
